version: '3'

services:
  nginx-rtmp-hls:
    container_name: nginx-rtmp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1935:1935"  # RTMP 포트
      - "80:80"      # HTTP 포트
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf